/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package app;

import org.assertj.core.api.WithAssertions;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.junit.jupiter.MockitoExtension;

@ExtendWith(MockitoExtension.class)
class MainTest implements WithAssertions {

    @Test
    void appHasAGreeting() {
        Main classUnderTest = new Main();
    }
}
