/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package app;

import app.config.General;
import app.enums.StateVehicle;
import app.model.Car;
import app.model.LightSailboat;
import app.usecase.VehicleAdapter;
import com.google.inject.Guice;
import com.google.inject.Injector;
import java.util.Scanner;
import lombok.extern.slf4j.Slf4j;

@Slf4j
public class Main {

//  private static final Logger logger = Logger.getLogger(Main.class.getName());

  public static void main(String[] args) {

    // Configura el logger para mostrar información detallada
    // Logger guiceLogger = Logger.getLogger("com.google.inject");
    // guiceLogger.setLevel(java.util.logging.Level.ALL);

    // Injector injector = Guice.createInjector(new General());

    // Imprime información sobre los bindings configurados en el módulo
    // System.out.println("Bindings en el módulo:");
    // injector.getAllBindings().forEach((key, binding) -> System.out.println(key + " -> " +
    // binding));


    Injector injector = Guice.createInjector(new General());
    final var adapter = injector.getInstance(VehicleAdapter.class);

    Scanner scanner = new Scanner(System.in);
    boolean exit = false;

    while (!exit) {
      System.out.println("Menú:");
      System.out.println("1. Crear un coche");
      System.out.println("2. Crear un velero ligero");
      System.out.println("3. Salir");
      System.out.print("Seleccione una opción: ");

      int option = scanner.nextInt();

      switch (option) {
        case 1:
          Car car = adapter.createCar(StateVehicle.NEW);
          System.out.println("Coche creado: " + car);
          break;
        case 2:
          LightSailboat boat = adapter.createLightSailboat(StateVehicle.NEW);
          System.out.println("Velero ligero creado: " + boat);
          break;
        case 3:
          exit = true;
          System.out.println("Saliendo del programa...");
          break;
        default:
          System.out.println("Opción no válida. Intente de nuevo.");
      }
    }
    scanner.close();
  }
}
